[tool.poetry]
name = "krux-installer"
version = "0.0.2-alpha-1"
description = "A GUI based application to flash Krux firmware on K210 based devices"
authors = [
  "qlrd <qlrddev@gmail.com>"
]
license = "LICENSE"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
kivy = "2.3.0"
kivysome = "^0.2.1"
tomli = { version = "^2.0.1", python = "<3.11" }
pyserial = "^3.5"
requests = "^2.31.0"
pyzbar = "^0.1.9"
opencv-python = "^4.9.0.80"
cryptography = "^42.0.5"
qrcode = "^7.4.2"
easy-i18n = "^1.2.0"
pysudoer = {git = "https://github.com/qlrd/pysudoer.git"}
distro = "^1.9.0"
pillow = "^10.4.0"

[tool.poetry.group.dev.dependencies]
black = "^24.1.1"
pylint = "^3.0.3"
pyinstaller = "^6.3.0"
pytest-cov = "^4.1.0"
poethepoet = "^0.25.1"
demjson3 = "^3.0.6"

[tool.poe.tasks]
cli = "python src/krux-installer.py"
format-src= "black ./src"
format-tests= "black ./tests"
format-e2e= "black ./e2e"
format-installer = "black ./krux-installer.py"
format = ["format-src", "format-tests", "format-e2e", "format-installer"]

test-unit = "pytest --cache-clear --cov=src/utils/constants --cov=src/utils/info --cov=src/utils/selector --cov=src/utils/downloader --cov=src/utils/trigger --cov=src/utils/flasher --cov=src/utils/unzip --cov=src/utils/signer --cov=src/utils/verifyer --cov=src/i18n --cov-branch --cov-report html ./tests"
test-e2e = "pytest --cov-append --cov=src/app --cov-branch --cov-report html ./e2e"
test = ["test-unit", "test-e2e"]

coverage-unit = "pytest --cache-clear --cov=src/utils/constants --cov=src/utils/info --cov=src/utils/selector --cov=src/utils/downloader --cov=src/utils/trigger --cov=src/utils/flasher --cov=src/utils/unzip --cov=src/utils/signer --cov=src/utils/verifyer --cov=src/i18n --cov-branch --cov-report xml ./tests"
coverage-e2e = "pytest --cov-append --cov=src/app --cov-branch --cov-report xml ./e2e"
coverage = ["coverage-unit", "coverage-e2e"]

patch-nix = "sh .ci/patch-pyinstaller-kivy-hook.sh"
patch-win = "powershell.exe -File .ci/patch-pyinstaller-kivy-hook.ps1"

clean-mac = "find . -name '.DS_Store' -delete"

lint.sequence = [
  { cmd = "jsonlint src/i18n/*.json"},
  { cmd = "pylint --rcfile .pylint/src ./src" },
  { cmd = "pylint --rcfile .pylint/tests ./tests"},
  { cmd = "pylint --rcfile=.pylint/tests ./e2e"}
]

[tool.poe.tasks.build-deb]
interpreter = "bash"
shell = """
python .ci/create-spec.py
python -m PyInstaller krux-installer.spec
NAME="$(python -c 'from src.utils.constants import get_name; print(get_name())')"
VER="$(python -c 'from src.utils.constants import get_version; print(get_version())')"
mkdir -p ./release
create-dmg --volname "${NAME}" --volicon ./assets/icon.icns --window-pos 200 120 --window-size 800 400 --icon-size 100 --icon "${NAME}.app" 200 190 --app-drop-link 600 185 "./release/${NAME}_${VER}_${ARCH}.dmg" "./dist/${NAME}.app"
"""

[tool.poe.tasks.build-rpm]
interpreter = "bash"
shell = """
python .ci/create-spec.py
python -m PyInstaller krux-installer.spec
NAME="$(python -c 'from src.utils.constants import get_name; print(get_name())')"
VER="$(python -c 'from src.utils.constants import get_version; print(get_version())')"
RPM_VERSION=$(sed -e 's/-/_/g' <<< $VERSION)
mkdir -p ./release
sh .ci/create-rpm.sh -a "${NAME}" -v $RPM_VERSION -m qlrd -e qlrddev@gmail.com -d "${DESCRIPTION}" -c ./CHANGELOG.md -r ./README.md -b "./dist/${NAME}" -i ./assets/icon.png
rpmbuild -vv -bb --define "_bindir /usr/local/bin" $HOME/rpmbuild/SPECS/$NAME.spec
"""

[tool.poe.tasks.build-dmg]
interpreter = "zsh"
shell = """
python .ci/create-spec.py
python -m PyInstaller krux-installer.spec
NAME="$(python -c 'from src.utils.constants import get_name; print(get_name())')"
VER="$(python -c 'from src.utils.constants import get_version; print(get_version())')"
mkdir -p ./release
create-dmg --volname "${NAME}" --volicon ./assets/icon.icns --window-pos 200 120 --window-size 800 400 --icon-size 100 --icon "${NAME}.app" 200 190 --app-drop-link 600 185 "./release/${NAME}_${VER}_${ARCH}.dmg" "./dist/${NAME}.app"
"""

[tool.pow.tasks.build-win]
interpreter = ["pwsh", "powershell"]
shell = """
$releasePath = ".\\release"
$name = python -c 'from src.utils.constants import get_name; print(get_name())'
$version = python -c 'from src.utils.constants import get_version; print(get_version())'
$description= python -c 'from src.utils.constants import get_description; print(get_description())'

if (-not (Test-Path -Path $releasePath)) {
  New-Item -Path $releasePath -ItemType Directory
} else {
  if (Test-Path -Path "$releasePath\\krux-installer_v$version Setup.exe") {
    Remove-Item ".\\release\\krux-installer_v$version Setup.exe"
  }
}

python .ci\\create-spec.py
.ci\\edit-spec.ps1
python -m PyInstaller krux-installer.spec
python .ci\\create-nsis.py -a $name -b .\\dist\\krux-installer.exe -o selfcustody -V $version -d "$description" -l .\\LICENSE -i .\\assets\\icon.ico -O .
makensis.exe .\\krux-installer.nsi
Move-Item -Path ".\\krux-installer Setup.exe" -Destination ".\\release\\krux-installer_v$version Setup.exe"
"""

[tool.poe.tasks.dev-debug]
env = { LOGLEVEL = "debug" }
cmd = "python krux-installer.py"

[tool.poe.tasks.dev]
env = { LOGLEVEL = "info" }
cmd = "python krux-installer.py"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
