[tool.poetry]
name = "krux-installer"
version = "0.0.2"
description = "A GUI based application to flash Krux firmware on K210 based devices"
authors = [
  "qlrd <qlrddev@gmail.com>"
]
license = "LICENSE"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<=3.11.7"
kivy = "^2.2.1"
kivysome = "^0.2.1"
pyopenssl = "^24.0.0"
pytest-cov = "^4.1.0"
tomli = { version = "^2.0.1", python = "<3.11" }

[tool.poetry.group.dev.dependencies]
black = "^24.1.1"
pylint = "^3.0.3"
pyinstaller = "^6.3.0"
poethepoet = "^0.24.4"

[tool.poe.tasks]
cli = "python src/krux-installer.py"
format-src= "black ./src"
format-tests= "black ./tests"
format = ["format-src", "format-tests"]
lint-src = "pylint ./src"
lint-tests = "pylint --disable=C0114,C0115,C0116 ./tests"
lint = ["lint-src", "lint-tests"]
test = "pytest --capture=tee-sys --verbose --cache-clear ./tests "
coverage-html = "pytest --cache-clear --cov src/ --cov-report html ./tests"
coverage-xml = "pytest --cache-clear --cov src/ --cov-report xml ./tests"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
