[tool.poetry]
name = "krux-installer"
version = "0.0.2"
description = "A GUI based application to flash Krux firmware on K210 based devices"
authors = [
  "qlrd <qlrddev@gmail.com>"
]
license = "LICENSE"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.13"
kivy = "^2.2.1"
kivysome = "^0.2.1"
tomli = { version = "^2.0.1", python = "<3.11" }
pyserial = "^3.5"
requests = "^2.31.0"
pyzbar = "^0.1.9"
opencv-python = "^4.9.0.80"
cryptography = "^42.0.5"
qrcode = "^7.4.2"

[tool.poetry.group.dev.dependencies]
black = "^24.1.1"
pylint = "^3.0.3"
pyinstaller = "^6.3.0"
pytest-cov = "^4.1.0"
poethepoet = "^0.24.4"

[tool.pytest.coverage]
cov = [
]

[tool.poe.tasks]
cli = "python src/krux-installer.py"
format-src= "black ./src"
format-tests= "black ./tests"
format-installer = "black ./krux-installer.py"
format = ["format-src", "format-tests", "format-installer"]
lint-src = "pylint --ignore-paths=./src/utils/kboot ./src"
lint-tests = "pylint --disable=C0114,C0115,C0116,R0904 ./tests"
lint = ["lint-src", "lint-tests"]
test = "pytest --cache-clear --cov=src/utils/constants --cov=src/utils/info --cov=src/utils/selector --cov=src/utils/downloader --cov=src/utils/trigger --cov=src/utils/flasher --cov=src/utils/unzip --cov=src/utils/signer --cov=src/utils/verifyer --cov-report html ./tests"
coverage = "pytest --cache-clear --cov=src/utils/constants --cov=src/utils/info --cov=src/utils/selector --cov=src/utils/downloader --cov=src/utils/trigger --cov=src/utils/flasher --cov=src/utils/unzip --cov=src/utils/signer --cov=src/utils/verifyer --cov-report xml ./tests"
build = "python scripts/build.py"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
