name: Windows Build

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  build-on-linux:
    name: Build executable for windows (NSIS) on linux
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        targetos: [win]
        target: [nsis]
        node_version: ['16.18.0']
        include:
          - os: ubuntu-22.04
            alias: jammy
          - os: ubuntu-20.04
            alias: focal

    runs-on: ${{ matrix.os }}
 
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Install WINE for ubuntu
        run: |
          sudo dpkg --add-architecture i386
          wget -nc https://dl.winehq.org/wine-builds/winehq.key
          sudo mv winehq.key /usr/share/keyrings/winehq-archive.key
          wget -nc https://dl.winehq.org/wine-builds/ubuntu/dists/${{ matrix.alias }}/winehq-${{ matrix.alias }}.sources
          sudo mv winehq-${{ matrix.alias }}.sources /etc/apt/sources.list.d/
          sudo apt-get update
          sudo apt install --install-recommends winehq-devel

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install Node.js dependencies
        run: yarn install

      - name: Generate icons
        run: |
          yarn run icon:svg
          yarn run icon:png
          yarn run icon:resize
          yarn run icon:ico
          rm ./build/*.svg
          rm ./build/*.png

      - name: Build Krux Installer for linux
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: DEBUG=electron-builder yarn run electron:build --${{ matrix.targetos }} ${{ matrix.target }}


