name: Build electron application as AppImage on linux

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:

  build-linux:
    runs-on: ubuntu-latest
  
    steps:

      - name: Checkout Git repository
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Variables helpers
        id: setup
        run: |
          KRUX_VERSION=`node -e "console.log(require('./package.json').version)"`
          echo "app-version=$KRUX_VERSION" >> $GITHUB_OUTPUT
          KRUX_NAME=krux-installer-$KRUX_VERSION
          echo "app-name=$KRUX_NAME" >> $GITHUB_OUTPUT
          echo "::group::Variables"
          echo "app-version=$KRUX_VERSION"
          echo "app-name=$KRUX_NAME"
          echo "::endgroup::"

      - name: Restore cache build
        id: restore-cache-build
        uses: actions/cache/restore@v3 
        with:
          path: |
            release/${{ steps.setup.outputs.app-version }}/${{ steps.setup.outputs.app-name }}.AppImage
            release/${{ steps.setup.outputs.app-version }}/${{ steps.setup.outputs.app-name }}.AppImage.sha256.txt
            release/${{ steps.setup.outputs.app-version }}/linux-unpacked
          key: ${{ runner.os }}-${{ steps.setup.outputs.app-name }}-AppImage-${{ hashFiles('dist-electron/**') }}

      - name: Install dependencies 
        if: ${{ steps.restore-cache-build.outputs.cache-hit != 'true' }}
        run: yarn install

      - name: Build electron app
        if: ${{ steps.restore-cache-build.outputs.cache-hit != 'true' }}
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.token }}
        run: yarn run build --linux AppImage

      - name: Hash electron app (Linux)
        if: ${{ steps.restore-cache-build.outputs.cache-hit != 'true' }}
        uses: qlrd/sha256sum-action@v2
        with:
          working-directory: ./release/${{ steps.setup.outputs.app-version }}
          file: ${{ steps.setup.outputs.app-name }}.AppImage
          ext: sha256.txt

      - name: List release files
        run: |
          echo "::group::Release files"
          ls -la release/${{ steps.setup.outputs.app-version }}
          echo "::endgroup::"

      - name: Save cache build
        if: ${{ steps.restore-cache-build.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v3
        with:
          path: |
            release/${{ steps.setup.outputs.app-version }}/${{ steps.setup.outputs.app-name }}.AppImage
            release/${{ steps.setup.outputs.app-version }}/${{ steps.setup.outputs.app-name }}.AppImage.sha256.txt
            release/${{ steps.setup.outputs.app-version }}/linux-unpacked
          key: ${{ runner.os }}-${{ steps.setup.outputs.app-name }}-AppImage-${{ hashFiles('dist-electron/**') }}
