name: Build AppImage for Linux

on:
  push:
    branches:
      - main
      - linux-appimage-wdio
    pull_request:
      branches:
        - main

jobs:
  build:
    name: Build AppImage executable
          
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      # See 'Testing on Headless CI Systems'
      # https://github.com/electron/electron/blob/main/docs/tutorial/testing-on-headless-ci.md
      - name: Setup Xvfb for headless tests
        run: sudo apt-get install -y xvfb
      
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.18.0'

      - name: Install dependencies
        run: |
          yarn install
          yarn platform-install
      
      - name: Make icons
        run: |
          yarn run icon
          rm ./build/*.svg
          rm ./build/krux.png

      - name: Get version
        uses: polyseam/get-version-from-package-json@1.0.0
        id: version
        with:
          path-to-package-json: ./package.json

      - name: Lint
        run: yarn run lint

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: yarn run build AppImage
    
      - name: E2E Test
        run: yarn run test

      - name: Hash executable
        uses: qlrd/sha256sum-action@v1.0.0
        with:
          path-to-file: dist_electron/KruxInstaller-${{ steps.version.outputs.version }}.AppImage


      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: KruxInstaller-v${{ steps.version.outputs.version }}.AppImage
          path: |
            dist_electron/KruxInstaller-${{ steps.version.outputs.version }}.AppImage
            dist_electron/KruxInstaller-${{ steps.version.outputs.version }}.AppImage.sha256sum.txt
