name: Linux Build

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  build:
    name: Build executables (AppImage) for linux
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        targetos: [linux]
        target: [AppImage]
        node_version: ['16.18.0']

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install Node.js dependencies
        run: yarn install

      - name: Generate icons
        run: |
          yarn run icon:svg
          yarn run icon:png
          yarn run icon:resize
          rm ./build/*.svg
          rm ./build/krux.png

      - name: Build Krux Installer for linux
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: DEBUG=electron-builder yarn run electron:build --${{ matrix.targetos }} ${{ matrix.target }}
