name: Build NSIS installer for windows

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  build:
    name: Build NSIS installer for windows
          
    runs-on: windows-latest
    
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.18.0'

      - name: Install Node.js dependencies (Windows)
        run: |
          yarn install
          yarn run platform-install

      - name: Make icons
        run: |
          yarn run icon
          rm ./build/*.svg
          rm ./build/*.png

      - name: Get version from package.json
        uses: polyseam/get-version-from-package-json@1.0.0
        id: version
        with:
          path-to-package-json: ./package.json

      - name: Build KruxInstaller
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: |
          yarn run build nsis
      
      - name: Hash executable
        uses: qlrd/sha256sum-action@v1.0.0
        with:
          path-to-file: dist_electron/KruxInstaller-${{ steps.version.outputs.version }}.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: KruxInstaller-v${{ steps.version.outputs.version }}.exe
          path: |
            dist_electron/KruxInstaller-${{ steps.version.outputs.version }}.exe
            dist_electron/KruxInstaller-${{ steps.version.outputs.version }}.exe.sha256sum.txt
