name: Windows Build

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  build-on-linux:
    name: Build executable for windows (NSIS) on linux
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        targetos: [win]
        target: [nsis]
        node_version: ['16.18.0']

    runs-on: ${{ matrix.os }}
 
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Prepare WINE installation
        run: |
          sudo dpkg --add-architecture i386
          sudo mkdir -pm755 /etc/apt/keyrings
          sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key

      - name: Download WINE sources for Ubuntu-22.04 
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources

      - name: Download WINE sources for Ubuntu-20.04 
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-focal.sources

      - name: Install WINE
        run: |
          sudo apt-get update
          sudo apt install --install-recommends winehq-stable

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install Node.js dependencies
        run: yarn install

      - name: Generate icons
        run: |
          yarn run icon:svg
          yarn run icon:png
          yarn run icon:resize
          yarn run icon:ico
          rm ./build/*.svg
          rm ./build/*.png

      - name: Build Krux Installer for linux
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: DEBUG=electron-builder yarn run electron:build --${{ matrix.targetos }} ${{ matrix.target }}


