name: Build

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  build:
    name: Build executables 
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            platform: linux
            target: AppImage
            node_version: '16.18.0'

          - os: ubuntu-20.04
            platform: linux
            target: AppImage
            node_version: '16.18.0'
          
          - os: ubuntu-22.04
            platform: linux
            target: deb
            node_version: '16.18.0'

          - os: ubuntu-20.04
            platform: linux
            target: deb
            node_version: '16.18.0'
          
          - os: windows-latest
            platform: win
            target: nsis
            node_version: '16.18.0'

          - os: windows-latest
            platform: win
            target: portable
            node_version: '16.18.0'

          - os: windows-latest
            platform: win
            target: msi
            node_version: '16.18.0'

          - os: windows-2019
            platform: win
            target: nsis
            node_version: '16.18.0'

          - os: windows-2019
            platform: win
            target: portable
            node_version: '16.18.0'

          - os: windows-2019
            platform: win
            target: msi
            node_version: '16.18.0'

          - os: macos-12
            platform: macos
            target: dmg
            node_version: '16.18.0'

          - os: macos-11
            platform: macos
            target: dmg
            node_version: '16.18.0'

          - os: macos-10.15
            platform: macos
            target: dmg
            node_version: '16.18.0'
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install Node.js dependencies (Linux or Windows)
        if: ${{ matrix.platform != 'macos' }}
        run: yarn install --omit=optional

      - name: Install Node.js dependencies (MacOS)
        if: ${{ matrix.platform == 'macos' }}
        run: yarn install
      
      - name: Prepare icons
        run: |
          yarn run icon:svg
          yarn run icon:png
          yarn run icon:resize

      - name: Adequate icons for linux
        if: ${{ matrix.platform == 'linux' }}
        run: |
          rm ./build/*.svg
          rm ./build/krux.png

      - name: Adequate icons for windows
        if: ${{ matrix.platform == 'win' }}
        run: |
          yarn run icon:ico
          rm ./build/*.svg
          rm ./build/*.png

      - name: Adequate icons for MacOS
        if: ${{ matrix.platform == 'macos' }}
        run: |
          yarn run icon:icns
          rm ./build/*.svg
          rm ./build/*.png

      - name: Build KruxInstaller
        id: buildKruxInstaller
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: yarn run electron:build --${{ matrix.platform }} ${{ matrix.target }}

      - name: Get version from package.json
        uses: polyseam/get-version-from-package-json@1.0.0
        id: version
        with:
          path-to-package-json: ./package.json

      - name: Move binary to root (relative to project)
        run: mv dist_electron/KruxInstaller-${{ steps.version.outputs.version }}.${{ matrix.target }}  KruxInstaller-v${{ steps.version.outputs.version}}.${{ matrix.target }}

      - name: Hash executable
        uses: qlrd/sha256sum-action@v1.0.0
        id: sha256sum
        with:
          path-to-file:
            KruxInstaller-v${{ steps.version.outputs.version }}.${{ matrix.target }}
          
      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.named.outputs.app }} artifacts
          path: |
            KruxInstaller-v${{ steps.version.outputs.version }}.${{ matrix.target }}
            ${{ steps.sha256sum.outputs.hash-file }}

