name: Build NSIS installer for windows

on:
  push:
    branches:
      - main
      - win32-builtin-openssl
    pull_request:
      branches:
        - main

jobs:
  build:
    name: Build NSIS installer for windows
          
    runs-on: windows-latest
    
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Setup output variables helpers
        id: setup
        shell: pwsh
        run: |
          $loc = Get-Location
          mkdir $loc\vendor
          echo "prefix=$loc\vendor\OpenSSL" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append  
          echo "openssldir=$loc\vendor\OpenSSL\CommonFiles" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Configure, build, test and install openssl
        uses: qlrd/compile-openssl-windows-action@v0.0.1
        with:
          version: openssl-3.0.7
          prefix: ${{ steps.setup.outputs.prefix }}
          openssldir: ${{ steps.setup.outputs.openssldir }}
          build-type: 'minimal'

      - name: Pre-test builtin openssl
        shell: pwsh
        run:
          ${{ steps.setup.outputs.prefix }}\bin\openssl.exe version
          ${{ steps.setup.outputs.prefix }}\bin\openssl.exe rand -hex 16
          $loc = Get-Location
          $version = "v22.08.2"
          curl.exe -LO https://github.com/selfcustody/krux/releases/download/$version/krux-$version.zip
          curl.exe -LO https://github.com/selfcustody/krux/releases/download/$version/krux-$version.zip.sig
          curl.exe -LO https://raw.githubusercontent.com/selfcustody/krux/main/selfcustody.pem
          ${{ steps.setup.output.prefix }}\bin\openssl.exe sha256 <$loc\krux-$version.zip -binary | ${{ steps.setup.output.prefix }}\bin\openssl.exe pkeyutl -verify -pubin -inkey $loc\selfcustody.pem -sigfile $loc\krux-$version.zip.sig

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.18.0'

      - name: Install Node.js dependencies (Windows)
        run: |
          yarn install
          yarn run platform-install

      - name: Make icons
        run: |
          yarn run icon
          rm ./build/*.svg
          rm ./build/*.png

      - name: Get version from package.json
        uses: polyseam/get-version-from-package-json@1.0.0
        id: version
        with:
          path-to-package-json: ./package.json

      - name: Build KruxInstaller
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: |
          yarn run build nsis
      
      - name: Hash executable
        uses: qlrd/sha256sum-action@v1.0.0
        with:
          path-to-file: .\dist_electron\KruxInstaller Setup ${{ steps.version.outputs.version }}.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: KruxInstaller Setup v${{ steps.version.outputs.version }}.exe
          path: |
            .\dist_electron\KruxInstaller Setup ${{ steps.version.outputs.version }}.exe
            .\dist_electron\KruxInstaller Setup ${{ steps.version.outputs.version }}.exe.sha256sum.txt
