name: Build

on:
  push:
    branches: 
      - main
      - new-ui
    paths-ignore:
      - "**.md"
      #- "**.spec.js"
      - ".idea"
      - ".vscode"
      - ".dockerignore"
      - "Dockerfile"
      #- ".gitignore"
      #- ".github/**"
      #- "!.github/workflows/build.yml"

jobs:

  build-linux-appimage:
    uses: ./.github/workflows/build-linux-appimage.yml
    secrets: 
      token: ${{ secrets.github_token }}

  test-linux:
    needs: build-linux-appimage
    uses: ./.github/workflows/test-linux.yml

  upload-linux-appimage:
    needs: test-linux
    uses: ./.github/workflows/upload-linux-appimage.yml
