name: Build

on:
  push:
    branches: 
      - main
    paths-ignore:
      - "**.md"
      #- "**.spec.js"
      - ".idea"
      - ".vscode"
      - ".dockerignore"
      - "Dockerfile"
      - ".gitignore"
      #- ".github/**"
      #- "!.github/workflows/build.yml"

jobs:

  build-linux-appimage:
    uses: ./.github/workflows/build-linux-appimage.yml
    secrets: 
      token: ${{ secrets.github_token }}

  build-linux-deb:
    uses: ./.github/workflows/build-linux-deb.yml
    secrets: 
      token: ${{ secrets.github_token }}

  #build-linux-deb-arm64:
  #  uses: ./.github/workflows/build-linux-deb-arm64.yml
  #  secrets: 
  #    token: ${{ secrets.github_token }}
  #    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  
  #build-linux-rpm-arm64:
  #  uses: ./.github/workflows/build-linux-rpm-arm64.yml
  #  secrets: 
  #    token: ${{ secrets.github_token }}
  #    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      
  build-linux-rpm:
    uses: ./.github/workflows/build-linux-rpm.yml
    secrets: 
      token: ${{ secrets.github_token }}
      
  build-windows-nsis:
    uses: ./.github/workflows/build-windows-nsis.yml 
    secrets: 
      token: ${{ secrets.github_token }}

  #build-mac-dmg:
  #  uses: ./.github/workflows/build-mac-dmg.yml 
  #  secrets: 
  #    token: ${{ secrets.github_token }}
