name: Windows Build

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  build-on-linux:
    name: Build executable for windows (NSIS) on linux
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        targetos: [win]
        target: [nsis]
        node_version: ['16.18.0']

    runs-on: ${{ matrix.os }}
 
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Install WINE for ubuntu
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          wget -qO- https://dl.winehq.org/wine-builds/winehq.key | gpg --dearmor | sudo tee /usr/share/keyrings/winehq.key > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/winehq.key] https://dl.winehq.org/wine-builds/ubuntu/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/winehq.list
          sudo apt-get update
          sudo apt-get install -y --install-recommends libgphoto2-6
          sudo apt-get install -y --install-recommends nginx
          sudo apt-get install -y --install-recommends wine-devel
          sudo apt-get install -y --install-recommends wine-devel-amd64
          sudo apt-get install -y --install-recommends winehq-devel

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install Node.js dependencies
        run: yarn install

      - name: Generate icons
        run: |
          yarn run icon:svg
          yarn run icon:png
          yarn run icon:resize
          yarn run icon:ico
          rm ./build/*.svg
          rm ./build/*.png

      - name: Build Krux Installer for linux
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: DEBUG=electron-builder yarn run electron:build --${{ matrix.targetos }} ${{ matrix.target }}


