name: Lint and create icon

on:
  workflow_call:
    inputs:
      os:
        description: 'The OS where lint will run'
        type: string
        required: true

jobs:
  lint:
    runs-on: ${{ inputs.os }}
  
    steps:

      - name: Checkout Git repository
        uses: actions/checkout@v3

      - name: Setup cached node.js with dependencies (Linux)
        if: ${{ runner.os == 'Linux' }}
        uses: qlrd/setup-cached-node@main
        with:
          node-version: '18.15.0'
          cache-path: ${{ format('{0}/node_modules', github.workspace) }}
          cache-key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }} 
          run: |
            yarn install
            yarn run platform-install
            yarn run install-app-deps

      - name: Setup cached node.js with dependencies (Windows)
        if: ${{ runner.os == 'Windows' }}
        uses: qlrd/setup-cached-node@main
        with:
          node-version: '18.15.0' 
          cache-path: ${{ format('{0}/node_modules', github.workspace) }}
          cache-key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock', format('{0}/node_modules/png-to-ico/bin', github.workspace)) }} 
          run: |
            yarn install
            yarn run platform-install
            yarn run install-app-deps

      - name: Lint (Linux)
        if: ${{ runner.os == 'Linux' }}
        shell: bash
        run: yarn run lint

      - name: Lint (Windows)
        if: ${{ runner.os == 'Windows' }}
        shell: pwsh
        run: yarn run lint 

      - name: Create Icon (Windows)
        if: ${{ runner.os == 'Windows' }}
        shell: pwsh
        run: yarn run icon
