name: Tests

on:
  push:
    branches:
      - kivy
      
  pull_request:

jobs:
  
  black:

    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry
        
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'
          cache-dependency-path: './poetry.lock'
          architecture: x64
      
      - name: Install poetry dependencies
        run: poetry install

      - name: Check format/
        run: |
          poetry run poe format-src --check --verbose
          poetry run poe format-tests --check --verbose
          poetry run poe format-e2e --check --verbose
          poetry run poe format-installer --check --verbose
          
  pylint:

    needs: black
    
    runs-on: ubuntu-latest
    
    steps:
      
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'
          cache-dependency-path: './poetry.lock'
          architecture: x64

      - name: Install poetry dependencies
        run: poetry install
        
      - name: Lint src/
        run: poetry run poe lint

  # from xPsycHoWasPx in discord chat:
  # "running macOS in none gpu accelerated mode, and that means no OpenGL,
  # no OpenGL no kivy window…. if u need to use vm, you also need a dedicated
  # seperate supported GPU passed through to the osx VM .."
  # 
  # TODO: find how to install properly libs for M1/M2 Macs
  # they raise exceptions that numpy and others libs
  # arent compiled for arm64 (macos-14 and macos-xlarge-*)
  
  pytest:

    needs: pylint

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
            
          - os: windows-latest
            arch: x64
                        
          - os: macos-13
            arch: x64
            
          - os: macos-14
            arch: arm64
        
    runs-on: ${{ matrix.os }}
    
    steps:
      
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v5
        if: ${{ matrix.arch != 'arm64' }}
        with:
          python-version: '3.12'
          cache: 'poetry'
          cache-dependency-path: './poetry.lock'
          architecture: ${{ matrix.arch }}

      - uses: actions/setup-python@v5
        if: ${{ matrix.arch == 'arm64' }}
        with:
          python-version: '3.12'
                 
      - name: Install project and its dependencies
        run: poetry install
        
      - name: Run tests with coverage (Linux)
        if: ${{ runner.os == 'Linux' }}
        uses: coactions/setup-xvfb@6b00cf1889f4e1d5a48635647013c0508128ee1a
        with:
          run: |
            poetry add pytest-xvfb
            poetry run poe coverage
            
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v4
        if: ${{ runner.os == 'Linux' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

      - name: Run tests (MacOS)
        if: ${{ runner.os == 'macOS' }}
        run: poetry run poe test-unit
        
      - name: Run tests (Windows)
        if: ${{ runner.os == 'Windows' }}
        env:
          KIVY_GL_BACKEND: 'angle_sdl2'
        run: poetry run poe test

      #- name: Run tests (MacOS)
      #  if: ${{ runner.os == 'macOS' }}
      #  env:
      #    KIVY_GL_DEBUG: 1
      #    KIVY_GL_BACKEND: 'gl'
      #  run: poetry run poe test
  
  build:

    needs: pytest
    
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
            
          - os: windows-latest
            arch: x64
            
          - os: macos-13
            arch: x64
            
          - os: macos-14
            arch: arm64
     
    runs-on: ${{ matrix.os }}
    
    steps:
      
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v5
        if: ${{ matrix.arch != 'arm64' }}
        with:
          python-version: '3.12'
          cache: 'poetry'
          cache-dependency-path: './poetry.lock'
          architecture: ${{ matrix.arch }}

      - uses: actions/setup-python@v5
        if: ${{ matrix.arch == 'arm64' }}
        with:
          python-version: '3.12'

      - name: Setup (Linux)
        if: ${{ runner.os == 'Linux' }}
        id: setup-linux
        run: |
          sudo apt-get install tree rpm
          mkdir -p ./release
          NAME="$(poetry run python -c 'from src.utils.constants import get_name; print(get_name())')"
          VERSION="$(poetry run python -c 'from src.utils.constants import get_version; print(get_version())')"
          DESCRIPTION="$(poetry run python -c 'from src.utils.constants import get_description; print(get_description())')"
          echo "name=${NAME}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "description=${DESCRIPTION}" >> $GITHUB_OUTPUT
      
      - name: Setup (MacOS)
        if: ${{ runner.os == 'macOS' }}
        id: setup-macos
        run: |
          brew install create-dmg
          brew reinstall openssl@3
          brew unlink openssl@3 && brew link openssl@3
          #OPENSSL_MAJOR_VERSION=`$(which openssl) -version | awk '{ print $2}' | cut -d . -f1` 
          OPENSSL_FULL_VERSION=`$(which openssl) -version | awk '{ print $2}'`
          OPENSSL_PATH="/opt/homebrew/Cellar/openssl@3/${OPENSSL_FULL_VERSION}"
          echo "dyld-path=${OPENSSL_PATH}/lib" >> $GITHUB_OUTPUT
         
      - name: Install project and its dependencies
        run: poetry install

      - name: Patch pyinstaller_hook for kivy in Unix
        if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
        run: poetry run poe patch-nix

      - name: Patch pyinstaller_hook for kivy in Windows
        if: ${{ runner.os == 'Windows' }}
        run: poetry run poe patch-win
        
      - name: Build dist (Linux)
        if: ${{ runner.os == 'Linux' }}
        uses: coactions/setup-xvfb@90473c3ebc69533a1a6e0505c36511b69c8c3135
        with:
          run: |
            poetry add pytest-xvfb
            poetry run poe build

      - name: Build dist (MacOS)
        if: ${{ runner.os == 'macOS' }}
        env:
          DYLD_LIBRARY_PATH: ${{ steps.setup-macos.outputs.dyld-path }}
        run: |
          poetry run poe clean-mac
          poetry run poe build
        
      - name: Build dist (Windows)
        if: ${{ runner.os == 'Windows' }}
        env:
          KIVY_GL_BACKEND: 'angle_sdl2'
        run: poetry run poe build
          
      - name: Build release deb (Linux)
        if: ${{ runner.os == 'Linux' }}
        id: release-deb
        env:
          NAME: ${{ steps.setup-linux.outputs.name }}
          VERSION: ${{ steps.setup-linux.outputs.version }}
          DESCRIPTION: ${{ steps.setup-linux.outputs.description }}
        run: |
          sh .ci/create-deb.sh \
            -a "${NAME}" \
            -o ./release \
            -v $VERSION \
            -A amd64 \
            -m qlrd \
            -e qlrddev@gmail.com \
            -d "${DESCRIPTION}" \
            -b "./dist/${NAME}" \
            -i ./assets/icon.png
          tree ./release    
          echo "pkg=${NAME}_${VERSION}_amd64.deb" >> $GITHUB_OUTPUT
  
      - name: Build release rpm (Linux)
        if: ${{ runner.os == 'Linux' }}
        id: release-rpm
        env:
          NAME: ${{ steps.setup-linux.outputs.name }}
          VERSION: ${{ steps.setup-linux.outputs.version }}
          DESCRIPTION: ${{ steps.setup-linux.outputs.description }}
        run: |
          RPM_VERSION=$(sed -e 's/-/_/g' <<< $VERSION)
          sh .ci/create-rpm.sh \
            -a "${NAME}" \
            -o ./release \
            -v $RPM_VERSION \
            -m qlrd \
            -e qlrddev@gmail.com \
            -d "${DESCRIPTION}" \
            -b "./dist/${NAME}" \
            -i ./assets/icon.png
          tree ./release
          rpmbuild --define "_topdir $(pwd)/release/rpmbuild" ./release/rpmbuild/SPECS/$NAME.spec
          
          echo "pkg=${NAME}-${VERSION}-1.x86_64.rpm" >> $GITHUB_OUTPUT
      
      - name: Build release dmg (MacOS)
        if: ${{ runner.os == 'macOS' }}
        id: release-macos
        run: |
          NAME="$(poetry run python -c 'from src.utils.constants import get_name; print(get_name())')"
          VER="$(poetry run python -c 'from src.utils.constants import get_version; print(get_version())')"
          ARCH="$(uname -m)"
          mkdir -p ./release
          create-dmg --volname "${NAME}" --volicon ./assets/icon.icns --window-pos 200 120 --window-size 800 400 --icon-size 100 --icon "${NAME}.app" 200 190 --app-drop-link 600 185 "./release/${NAME}_${VER}_${ARCH}.dmg" "./dist/${NAME}.app"
          echo "release-dmg=${NAME}_${VER}_${ARCH}.dmg" >> $GITHUB_OUTPUT

      - name: Build release NSIS (Windows)
        if: ${{ runner.os == 'Windows' }}
        id: release-windows
        shell: pwsh
        run: |
          Get-ChildItem -Path .\dist\
          choco --yes install nsis 
          New-Item ".\release" -Type Directory
          $name = poetry run python -c 'from src.utils.constants import get_name; print(get_name())'
          $version = poetry run python -c 'from src.utils.constants import get_version; print(get_version())'
          $description = poetry run python -c 'from src.utils.constants import get_description; print(get_description())'
          poetry run python .ci/create-nsis.py -a $name -b .\dist\krux-installer.exe -o selfcustody -V $version -d "$description" -l .\LICENSE -i .\assets\icon.ico -O .
          Get-Content -Path .\krux-installer.nsi
          makensis.exe .\krux-installer.nsi
          Move-Item -Path ".\krux-installer Setup.exe" -Destination ".\release\krux-installer_v$version Setup.exe"
          echo "release-nsis=krux-installer_v$version Setup.exe" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append 
            
      - name: Hash (Linux deb)
        if: ${{ runner.os == 'Linux' }}
        uses: qlrd/sha256sum-action@v2
        id: hash-deb
        with:
          working-directory: ./release
          file: ${{ steps.release-deb.outputs.pkg }}
          ext: 'sha256.txt'
          
      - name: Hash (Linux rpm)
        if: ${{ runner.os == 'Linux' }}
        uses: qlrd/sha256sum-action@v2
        id: hash-rpm
        with:
          working-directory: ./release
          file: ${{ steps.release-rpm.outputs.pkg }}
          ext: 'sha256.txt'
          
      - name: Hash (MacOS)
        if: ${{ runner.os == 'macOS' }}
        uses: qlrd/sha256sum-action@v2
        id: hash-macos
        with:
          working-directory: ./release
          file: ${{ steps.release-macos.outputs.release-dmg }}
          ext: 'sha256.txt'

      - name: Hash (Windows)
        if: ${{ runner.os == 'Windows' }}
        uses: qlrd/sha256sum-action@v2
        id: hash-win
        with:
          working-directory: .\release
          file: ${{ steps.release-windows.outputs.release-nsis }}
          ext: 'sha256.txt'

      - name: Upload artifact deb (Linux)
        if: ${{ runner.os == 'Linux' }}
        uses: actions/upload-artifact@v4         
        with:
          name: ${{ steps.release-deb.outputs.pkg }}
          path: |
            ./release/${{ steps.release-deb.outputs.rpm }}
            ${{ steps.hash-deb.outputs.hash-file }}
      
      - name: Upload artifact rpm (Linux)
        if: ${{ runner.os == 'Linux' }}
        uses: actions/upload-artifact@v4         
        with:
          name: ${{ steps.release-rpm.outputs.rpm }}
          path: |
            ./release/${{ steps.release-rpm.outputs.pkg }}
            ${{ steps.hash-rpm.outputs.hash-file }}
            
      - name: Upload artifacts (MacOS)
        if: ${{ runner.os == 'macOS' }}
        uses: actions/upload-artifact@v4         
        with:
          name: ${{ steps.release-macos.outputs.release-dmg }}
          path: |
            ./release/${{ steps.release-macos.outputs.release-dmg }}
            ${{ steps.hash-macos.outputs.hash-file }}
      
      - name: Upload artifacts (Windows)
        if: ${{ runner.os == 'Windows' }}
        uses: actions/upload-artifact@v4         
        with:
          name: ${{ steps.release-windows.outputs.release-nsis }}
          path: |
            .\release\${{ steps.release-windows.outputs.release-nsis }}
            ${{ steps.hash-win.outputs.hash-file }}
