name: Upload electron app as artifact on Windows

on:
  workflow_call:

    inputs:

      digest-ext:
        description: 'The extension for sha256 digest file'
        type: string
        default: 'sha256.txt'

jobs:

  upload:
    runs-on: windows-latest
  
    steps:

      - name: Checkout Git repository
        uses: actions/checkout@v3

      - name: Setup cached node.js with dependencies
        uses: qlrd/setup-cached-node@main
        with:
          node-version: '18.15.0'
          cache-path: ${{ github.workspace }}/node_modules
          cache-key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock', 'node_modules/png-to-ico/bin') }}

      - name: Setup variables
        id: setup
        shell: pwsh
        run: |
          $app_version = node -e "console.log(require('./package.json').version)"
          $app_name="KruxInstaller Setup $app_version"
          echo "app-name=$app_name" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Restore cache build
        uses: actions/cache/restore@v3 
        with:
          path: |
            dist_electron/${{ steps.setup.outputs.app-name }}.exe 
            dist_electron/${{ steps.setup.outputs.app-name }}.exe.${{ inputs.digest-ext }}
            dist_electron/win-unpacked
          key: ${{ runner.os }}-build-${{ hashFiles('src/**', 'public/**', 'vue.config.js') }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os}}-${{ steps.setup.outputs.app-name }}
          path: |
            dist_electron/${{ steps.setup.outputs.app-name }}.exe
            dist_electron/${{ steps.setup.outputs.app-name }}.exe.${{ inputs.digest-ext }}
